// Generated by speccaster v0.2.0 — your suite, extend it freely.
// Regenerate from your latest spec, then the drift gate keeps spec / suite in sync:
//   npx speccaster init --spec <spec> --out <file> --force
// These node:test cases are committed to your repo on purpose.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');

const BASE = process.env.SPECCASTER_BASE_URL || "/api/v3";

describe("pet / PUT /pet", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"name\":\"doggie\",\"photoUrls\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /pet');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / POST /pet", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"name\":\"doggie\",\"photoUrls\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /pet');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / GET /pet/findByStatus", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/findByStatus?status=available`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /pet/findByStatus');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / GET /pet/findByTags", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/findByTags?tags=sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /pet/findByTags');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / GET /pet/{petId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/1`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /pet/{petId}');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / POST /pet/{petId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/1`, {
      method: "POST",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /pet/{petId}');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("pet / DELETE /pet/{petId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/1`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /pet/{petId}');
  });
});

describe("pet / POST /pet/{petId}/uploadImage", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pet/1/uploadImage`, {
      method: "POST",
      headers: { 'content-type': "application/octet-stream" },
      body: "\"sample\"",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /pet/{petId}/uploadImage');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("store / GET /store/inventory", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/store/inventory`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /store/inventory');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("store / POST /store/order", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/store/order`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"id\":10,\"petId\":198772,\"quantity\":7,\"shipDate\":\"2026-01-01T00:00:00Z\",\"status\":\"approved\",\"complete\":true}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /store/order');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("store / GET /store/order/{orderId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/store/order/1`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /store/order/{orderId}');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("store / DELETE /store/order/{orderId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/store/order/1`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /store/order/{orderId}');
  });
});

describe("user / POST /user", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"id\":10,\"username\":\"theUser\",\"firstName\":\"John\",\"lastName\":\"James\",\"email\":\"john@email.com\",\"password\":\"12345\",\"phone\":\"12345\",\"userStatus\":1}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /user');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("user / POST /user/createWithList", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/createWithList`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "[\"sample\"]",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /user/createWithList');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("user / GET /user/login", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/login`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /user/login');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/xml, got ' + ct.split(';')[0]);
  });
});

describe("user / GET /user/logout", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/logout`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /user/logout');
  });
});

describe("user / GET /user/{username}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /user/{username}');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("user / PUT /user/{username}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/sample`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"id\":10,\"username\":\"theUser\",\"firstName\":\"John\",\"lastName\":\"James\",\"email\":\"john@email.com\",\"password\":\"12345\",\"phone\":\"12345\",\"userStatus\":1}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /user/{username}');
  });
});

describe("user / DELETE /user/{username}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/user/sample`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /user/{username}');
  });
});

