// Generated by speccaster v0.2.0 — your suite, extend it freely.
// Regenerate from your latest spec, then the drift gate keeps spec / suite in sync:
//   npx speccaster init --spec <spec> --out <file> --force
// These node:test cases are committed to your repo on purpose.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');

const BASE = process.env.SPECCASTER_BASE_URL || "https://api.spotify.com/v1";

describe("Albums / GET /albums", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/albums`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /albums');
  });
});

describe("Albums / GET /albums/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/albums/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /albums/{id}');
  });
});

describe("Albums / GET /albums/{id}/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/albums/sample/tracks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /albums/{id}/tracks');
  });
});

describe("Artists / GET /artists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/artists?ids=2CIMQHirSU0MQqyYHq0eOx%2C57dN52uHvrHOxijzpIgu3E%2C1vCWHaC5f2uS3yhpwWbIA6`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /artists');
  });
});

describe("Artists / GET /artists/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/artists/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /artists/{id}');
  });
});

describe("Artists / GET /artists/{id}/albums", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/artists/sample/albums`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /artists/{id}/albums');
  });
});

describe("Artists / GET /artists/{id}/related-artists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/artists/sample/related-artists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /artists/{id}/related-artists');
  });
});

describe("Artists / GET /artists/{id}/top-tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/artists/sample/top-tracks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /artists/{id}/top-tracks');
  });
});

describe("Tracks / GET /audio-analysis/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audio-analysis/11dFghVXANMlKmJXsNCbNl`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audio-analysis/{id}');
  });
});

describe("Tracks / GET /audio-features", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audio-features?ids=7ouMYWpwJ422jRcDASZB7P%2C4VqPOruhp5EdPBeR92t6lQ%2C2takcwOaAZWiXQijPHIx7B`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audio-features');
  });
});

describe("Tracks / GET /audio-features/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audio-features/11dFghVXANMlKmJXsNCbNl`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audio-features/{id}');
  });
});

describe("Audiobooks / GET /audiobooks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audiobooks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audiobooks');
  });
});

describe("Audiobooks / GET /audiobooks/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audiobooks/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audiobooks/{id}');
  });
});

describe("Audiobooks / GET /audiobooks/{id}/chapters", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/audiobooks/sample/chapters`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /audiobooks/{id}/chapters');
  });
});

describe("Categories / GET /browse/categories", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/browse/categories`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /browse/categories');
  });
});

describe("Categories / GET /browse/categories/{category_id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/browse/categories/dinner`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /browse/categories/{category_id}');
  });
});

describe("Playlists / GET /browse/categories/{category_id}/playlists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/browse/categories/dinner/playlists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /browse/categories/{category_id}/playlists');
  });
});

describe("Playlists / GET /browse/featured-playlists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/browse/featured-playlists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /browse/featured-playlists');
  });
});

describe("Albums / GET /browse/new-releases", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/browse/new-releases`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /browse/new-releases');
  });
});

describe("Chapters / GET /chapters", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/chapters`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /chapters');
  });
});

describe("Chapters / GET /chapters/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/chapters/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /chapters/{id}');
  });
});

describe("Episodes / GET /episodes", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/episodes?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /episodes');
  });
});

describe("Episodes / GET /episodes/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/episodes/512ojhOuo1ktJprKbVcKyQ`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /episodes/{id}');
  });
});

describe("Markets / GET /markets", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/markets`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /markets');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("Users / GET /me", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me');
  });
});

describe("Albums / GET /me/albums", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/albums`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/albums');
  });
});

describe("Albums / PUT /me/albums", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/albums`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/albums');
  });
});

describe("Albums / DELETE /me/albums", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/albums`, {
      method: "DELETE",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/albums');
  });
});

describe("Albums / GET /me/albums/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/albums/contains`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/albums/contains');
  });
});

describe("Audiobooks / GET /me/audiobooks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/audiobooks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/audiobooks');
  });
});

describe("Audiobooks / PUT /me/audiobooks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/audiobooks`, {
      method: "PUT",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/audiobooks');
  });
});

describe("Audiobooks / DELETE /me/audiobooks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/audiobooks`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/audiobooks');
  });
});

describe("Audiobooks / GET /me/audiobooks/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/audiobooks/contains`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/audiobooks/contains');
  });
});

describe("Episodes / GET /me/episodes", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/episodes`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/episodes');
  });
});

describe("Episodes / PUT /me/episodes", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/episodes?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/episodes');
  });
});

describe("Episodes / DELETE /me/episodes", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/episodes`, {
      method: "DELETE",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/episodes');
  });
});

describe("Episodes / GET /me/episodes/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/episodes/contains?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/episodes/contains');
  });
});

describe("Users / GET /me/following", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/following?type=artist`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/following');
  });
});

describe("Users / PUT /me/following", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/following?type=artist&ids=2CIMQHirSU0MQqyYHq0eOx%2C57dN52uHvrHOxijzpIgu3E%2C1vCWHaC5f2uS3yhpwWbIA6`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/following');
  });
});

describe("Users / DELETE /me/following", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/following?type=artist&ids=2CIMQHirSU0MQqyYHq0eOx%2C57dN52uHvrHOxijzpIgu3E%2C1vCWHaC5f2uS3yhpwWbIA6`, {
      method: "DELETE",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/following');
  });
});

describe("Users / GET /me/following/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/following/contains?type=artist&ids=2CIMQHirSU0MQqyYHq0eOx%2C57dN52uHvrHOxijzpIgu3E%2C1vCWHaC5f2uS3yhpwWbIA6`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/following/contains');
  });
});

describe("Player / GET /me/player", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player`, {
      method: "GET",
    });
    const okCodes = ["200","204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/player');
  });
});

describe("Player / PUT /me/player", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"device_ids\":[\"74ASZWbe4lXaubB36ztrGX\"]}",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player');
  });
});

describe("Player / GET /me/player/currently-playing", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/currently-playing`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/player/currently-playing');
  });
});

describe("Player / GET /me/player/devices", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/devices`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/player/devices');
  });
});

describe("Player / POST /me/player/next", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/next`, {
      method: "POST",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /me/player/next');
  });
});

describe("Player / PUT /me/player/pause", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/pause`, {
      method: "PUT",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/pause');
  });
});

describe("Player / PUT /me/player/play", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/play`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"context_uri\":\"spotify:album:5ht7ItJgpBH7W6vJ5BqpPr\",\"offset\":{\"position\":5},\"position_ms\":0}",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/play');
  });
});

describe("Player / POST /me/player/previous", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/previous`, {
      method: "POST",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /me/player/previous');
  });
});

describe("Player / GET /me/player/queue", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/queue`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/player/queue');
  });
});

describe("Player / POST /me/player/queue", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/queue?uri=spotify%3Atrack%3A4iV5W9uYEdYUVa79Axb7Rh`, {
      method: "POST",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /me/player/queue');
  });
});

describe("Player / GET /me/player/recently-played", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/recently-played`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/player/recently-played');
  });
});

describe("Player / PUT /me/player/repeat", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/repeat?state=context`, {
      method: "PUT",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/repeat');
  });
});

describe("Player / PUT /me/player/seek", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/seek?position_ms=25000`, {
      method: "PUT",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/seek');
  });
});

describe("Player / PUT /me/player/shuffle", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/shuffle?state=true`, {
      method: "PUT",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/shuffle');
  });
});

describe("Player / PUT /me/player/volume", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/player/volume?volume_percent=50`, {
      method: "PUT",
    });
    const okCodes = ["204"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/player/volume');
  });
});

describe("Playlists / GET /me/playlists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/playlists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/playlists');
  });
});

describe("Shows / GET /me/shows", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/shows`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/shows');
  });
});

describe("Shows / PUT /me/shows", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/shows`, {
      method: "PUT",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/shows');
  });
});

describe("Shows / DELETE /me/shows", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/shows`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/shows');
  });
});

describe("Shows / GET /me/shows/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/shows/contains`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/shows/contains');
  });
});

describe("Users / GET /me/top/{type}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/top/artists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/top/{type}');
  });
});

describe("Tracks / GET /me/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/tracks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/tracks');
  });
});

describe("Tracks / PUT /me/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/tracks`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /me/tracks');
  });
});

describe("Tracks / DELETE /me/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/tracks`, {
      method: "DELETE",
      headers: { 'content-type': "application/json" },
      body: "{\"ids\":[\"sample\"]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /me/tracks');
  });
});

describe("Tracks / GET /me/tracks/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/me/tracks/contains`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /me/tracks/contains');
  });
});

describe("Playlists / GET /playlists/{playlist_id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /playlists/{playlist_id}');
  });
});

describe("Playlists / PUT /playlists/{playlist_id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"description\":\"Updated playlist description\",\"name\":\"Updated Playlist Name\",\"public\":false}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /playlists/{playlist_id}');
  });
});

describe("Users / PUT /playlists/{playlist_id}/followers", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/followers`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"public\":false}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /playlists/{playlist_id}/followers');
  });
});

describe("Users / DELETE /playlists/{playlist_id}/followers", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/followers`, {
      method: "DELETE",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /playlists/{playlist_id}/followers');
  });
});

describe("Users / GET /playlists/{playlist_id}/followers/contains", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/followers/contains?ids=jmperezperez%2Cthelinmichael%2Cwizzler`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /playlists/{playlist_id}/followers/contains');
  });
});

describe("Playlists / GET /playlists/{playlist_id}/images", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/images`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /playlists/{playlist_id}/images');
  });
});

describe("Playlists / PUT /playlists/{playlist_id}/images", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/images`, {
      method: "PUT",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /playlists/{playlist_id}/images');
  });
});

describe("Playlists / GET /playlists/{playlist_id}/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/tracks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /playlists/{playlist_id}/tracks');
  });
});

describe("Playlists / PUT /playlists/{playlist_id}/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/tracks`, {
      method: "PUT",
      headers: { 'content-type': "application/json" },
      body: "{\"insert_before\":3,\"range_length\":2,\"range_start\":1}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for PUT /playlists/{playlist_id}/tracks');
  });
});

describe("Playlists / POST /playlists/{playlist_id}/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/tracks`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"position\":1,\"uris\":[\"sample\"]}",
    });
    const okCodes = ["201"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /playlists/{playlist_id}/tracks');
  });
});

describe("Playlists / DELETE /playlists/{playlist_id}/tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/playlists/sample/tracks`, {
      method: "DELETE",
      headers: { 'content-type': "application/json" },
      body: "{\"tracks\":[{\"uri\":\"sample\"}]}",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for DELETE /playlists/{playlist_id}/tracks');
  });
});

describe("Tracks / GET /recommendations", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/recommendations?seed_artists=4NHQUGzhtTLFvgF5SZesLK&seed_genres=classical%2Ccountry&seed_tracks=0c6xIDDpzE81m2q797ordA`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /recommendations');
  });
});

describe("Genres / GET /recommendations/available-genre-seeds", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/recommendations/available-genre-seeds`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /recommendations/available-genre-seeds');
  });
});

describe("Search / GET /search", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/search?q=remaster%2520track%3ADoxy%2520artist%3AMiles%2520Davis&type=album`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /search');
  });
});

describe("Shows / GET /shows", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/shows`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /shows');
  });
});

describe("Shows / GET /shows/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/shows/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /shows/{id}');
  });
});

describe("Shows / GET /shows/{id}/episodes", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/shows/sample/episodes`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /shows/{id}/episodes');
  });
});

describe("Tracks / GET /tracks", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/tracks`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /tracks');
  });
});

describe("Tracks / GET /tracks/{id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/tracks/11dFghVXANMlKmJXsNCbNl`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /tracks/{id}');
  });
});

describe("Users / GET /users/{user_id}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/users/sample`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /users/{user_id}');
  });
});

describe("Playlists / GET /users/{user_id}/playlists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/users/sample/playlists`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /users/{user_id}/playlists');
  });
});

describe("Playlists / POST /users/{user_id}/playlists", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/users/sample/playlists`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"description\":\"New playlist description\",\"name\":\"New Playlist\",\"public\":false}",
    });
    const okCodes = ["201"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /users/{user_id}/playlists');
  });
});

