const fs = require('fs');
const path = require('path');
const yaml = require('yaml');
const { sampleFromSchema } = require('./sample');
const { queryEncoding, simplerPathValue } = require('./serialize');
const { createResolver } = require('./resolve');

const METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'];
const VERSION = require('../package.json').version;
const HEADER = `// Generated by speccaster v${VERSION} — your suite, extend it freely.
// Regenerate from your latest spec, then the drift gate keeps spec / suite in sync:
//   npx speccaster init --spec <spec> --out <file> --force
// These node:test cases are committed to your repo on purpose.
//
// NOTE: generated tests send real traffic. Mutating operations (POST/PUT/PATCH/DELETE)
// will modify the API they hit — point SPECCASTER_BASE_URL at a TEST environment.
`;

const JSON_PLUS_RE = /^application\/.*\+json$/;
const FORM_TYPES = ['application/x-www-form-urlencoded'];
const TEXT_TYPES = ['text/plain'];

function loadSpec(file) {
  const raw = fs.readFileSync(file, 'utf8');
  return /\.ya?ml$/i.test(file) ? yaml.parse(raw) : JSON.parse(raw);
}

function serverUrl(spec) {
  const servers = Array.isArray(spec.servers) && spec.servers.length ? spec.servers : null;
  if (!servers) return 'http://localhost:8080';
  const s = servers[0] && typeof servers[0] === 'object' ? servers[0] : { url: String(servers[0]) };
  let url = typeof s.url === 'string' ? s.url : 'http://localhost:8080';
  const vars = s.variables || {};
  url = url.replace(/\{([^}]+)\}/g, (m, k) => {
    const v = vars[k];
    const def = v && typeof v === 'object' && v.default !== undefined ? String(v.default) : (Array.isArray(v) && v[0] !== undefined ? String(v[0]) : '');
    return def;
  });
  return url;
}

function pickMediaType(keys) {
  const json = keys.find((k) => k === 'application/json');
  if (json) return json;
  const plus = keys.find((k) => JSON_PLUS_RE.test(k));
  if (plus) return plus;
  return keys.length ? keys[0] : null;
}

function collectOperations(spec, resolver) {
  const ops = [];
  const paths = spec.paths || {};
  for (const p of Object.keys(paths)) {
    const rawItem = paths[p];
    if (!rawItem || typeof rawItem !== 'object') continue;
    const item = resolver.resolve(rawItem);
    if (!item || typeof item !== 'object') continue;
    for (const m of METHODS) {
      const op = item[m];
      if (!op || typeof op !== 'object') continue;
      const merged = [];
      const seen = new Set();
      const pushOne = (pr) => {
        if (!pr || typeof pr !== 'object') return;
        const k = (pr.name || '') + ':' + (pr.in || '');
        if (seen.has(k)) return;
        seen.add(k);
        merged.push(pr);
      };
      (item.parameters || []).forEach(pushOne);
      (op.parameters || []).forEach(pushOne);
      ops.push({
        method: m.toUpperCase(),
        path: p,
        operationId: op.operationId || m.toUpperCase() + ' ' + p,
        summary: op.summary || '',
        params: merged,
        requestBody: op.requestBody,
        responses: op.responses || {},
        tags: op.tags || [],
      });
    }
  }
  return ops;
}

function sampleParam(p, resolver, mode) {
  let schema = p && p.schema ? p.schema : null;
  if (p && p.content) {
    const mt = pickMediaType(Object.keys(p.content));
    if (mt) schema = p.content[mt].schema || null;
  }
  const resolved = schema ? resolver.resolve(schema) : {};
  const v = sampleFromSchema(resolved, { resolve: resolver.resolve, mode: mode || 'request' });
  return v;
}

function buildPathSegments(pathStr, opParams, resolver) {
  const segs = pathStr.replace(/\{([^}]+)\}/g, (m, name) => {
    const p = opParams.find((x) => x && x.name === name && x.in === 'path');
    const v = sampleParam(p, resolver, 'request');
    if (v === undefined || v === null) return '{' + name + '}';
    return simplerPathValue(p, v);
  });
  return segs;
}

function buildQuery(opParams, resolver) {
  const pairs = [];
  for (const p of opParams) {
    if (!p || p.in !== 'query') continue;
    if (!p.required) continue;
    const v = sampleParam(p, resolver, 'request');
    if (v === undefined || v === null) continue;
    pairs.push(...queryEncoding(p, v));
  }
  return pairs;
}

function expectedStatusKeys(op) {
  const responses = op.responses || {};
  if (!responses || typeof responses !== 'object') return ['2xx'];
  let keys = Object.keys(responses);
  const has2xx = keys.some((k) => /^2\d\d$/.test(k) || k === '2XX');
  if (!has2xx && keys.length) return keys;
  if (!keys.length) return ['2xx'];
  keys = keys.filter((k) => /^[1-5]\d\d$/.test(k) || /^[1-5]XX$/i.test(k) || k === 'default');
  return has2xx ? keys : (keys.length ? keys : ['2xx']);
}

function chooseValidationCode(op) {
  const keys = Object.keys(op.responses || {});
  const exact = keys.filter((k) => /^2\d\d$/.test(k)).sort();
  if (exact.length) return exact[0];
  if (keys.includes('2XX')) return '2XX';
  return null;
}

function resolveResponse(responses, code, resolver) {
  const entry = responses && responses[code];
  if (!entry) return null;
  return resolver.resolve(entry);
}

function bodyFor(op, spec, resolver, warnings) {
  let rb = op.requestBody;
  if (!rb) return null;
  rb = resolver.resolve(rb);
  const content = rb && rb.content ? rb.content : {};
  const keys = Object.keys(content);
  const jsonKey = keys.find((k) => k === 'application/json');
  const plusKey = keys.find((k) => JSON_PLUS_RE.test(k));
  const formKey = keys.find((k) => FORM_TYPES.includes(k));
  const textKey = keys.find((k) => TEXT_TYPES.includes(k));

  if (jsonKey) {
    const schema = content[jsonKey].schema;
    const value = sampleFromSchema(resolver.resolve(schema), { resolve: resolver.resolve, mode: 'request' });
    return { kind: 'json', content: JSON.stringify(value), contentType: jsonKey };
  }
  if (plusKey) {
    const schema = content[plusKey].schema;
    const value = sampleFromSchema(resolver.resolve(schema), { resolve: resolver.resolve, mode: 'request' });
    return { kind: 'json', content: JSON.stringify(value), contentType: plusKey };
  }
  if (formKey) {
    const schema = content[formKey].schema;
    const value = sampleFromSchema(resolver.resolve(schema), { resolve: resolver.resolve, mode: 'request' }) || {};
    const params = new URLSearchParams();
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      for (const k of Object.keys(value)) params.append(k, value[k] === null || value[k] === undefined ? '' : String(value[k]));
    }
    return { kind: 'form', content: params.toString(), contentType: formKey };
  }
  if (textKey) {
    const schema = content[textKey].schema;
    const value = sampleFromSchema(resolver.resolve(schema), { resolve: resolver.resolve, mode: 'request' });
    return { kind: 'text', content: value === null || value === undefined ? '' : String(value), contentType: textKey };
  }
  warnings.push(
    `[speccaster] ${op.method} ${op.path}: request body media ${keys[0] ? 'types ' + keys.join(', ') : 'undeclared'} are not auto-generated — the test is skipped; add the body manually (see README).`
  );
  return { kind: 'unsupported', contentType: keys[0] || null };
}

function testName(op) {
  const tag = op.tags && op.tags.length ? op.tags[0] + ' / ' : '';
  return tag + op.method + ' ' + op.path;
}

function renderResponseValidation(op, code, resolver) {
  // Returns { schemaLiteral, media } or null when the success response has no
  // usable body schema.
  const responses = op.responses || {};
  const resp = resolveResponse(responses, code, resolver);
  if (!resp) return null;
  const content = resp.content || {};
  const keys = Object.keys(content);
  if (!keys.length) return null;
  const media = pickMediaType(keys);
  if (!media) return null;
  const rawSchema = content[media].schema;
  if (!rawSchema) return null;
  const schema = resolver.materialize(rawSchema);
  return { schema, media };
}

function renderStatusAssertion(op, keys) {
  return (
    `    assert.ok(statusAllowed(String(res.status), ${JSON.stringify(keys)}),\n` +
    `      '${op.method} ${op.path} — expected status ' + ${JSON.stringify(keys.join('/'))} + ', got ' + res.status);\n`
  );
}

function contentTypeLine(op, opts) {
  const ct = opts.media;
  return (
    `    const ct = res.headers.get('content-type') || '';\n` +
    `    assert.ok(contentMatches(${JSON.stringify(ct)}, ct), '${op.method} ${op.path} — expected ${ct}, got ' + (ct.split(';')[0] || ct));\n`
  );
}

function renderBodyValidation(op, val) {
  if (!val || !val.schema) return '';
  const isText = /^text\//.test(val.media) || val.media === 'text/plain';
  const label = `${op.method} ${op.path}`;
  const bodyExpr = isText
    ? 'bodyText'
    : `(function(){ try { return JSON.parse(bodyText); } catch (e) { throw new Error(${JSON.stringify(label)} + ' — response body is not valid JSON: ' + e.message); } })()`;
  return (
    `    const bodyText = await res.text();\n` +
    `    if (res.status !== 204 && res.status >= 200 && res.status < 300) {\n` +
    `      const errs = schemaErrors(${bodyExpr}, SCHEMA, 'response.body');\n` +
    `      assert.equal(errs.length, 0, formatErrors(${JSON.stringify(label + ' — response does not match the declared schema')}, errs));\n` +
    `    }\n`
  );
}

function renderTest(op, spec, resolver, warnings) {
  const lines = [];
  const name = testName(op);
  const segs = buildPathSegments(op.path, op.params, resolver);
  const queryPairs = buildQuery(op.params, resolver);
  const qs = queryPairs.length ? '?' + queryPairs.map(([k, v]) => k + '=' + v).join('&') : '';
  const body = bodyFor(op, spec, resolver, warnings);

  const urlExpr = '`${BASE}` + ' + JSON.stringify(segs + qs);

  lines.push(`describe(${JSON.stringify(name)}, () => {`);

  const code = chooseValidationCode(op);
  const val = code ? renderResponseValidation(op, code, resolver) : null;
  const respVal = val && val.media ? val : null;
  if (respVal) {
    lines.push(`  const SCHEMA = ${JSON.stringify(respVal.schema)};`);
  }

  if (body && body.kind === 'unsupported') {
    const mt = body.contentType || 'unspecified';
    lines.push(`  test('skipped: request body not auto-generated (${mt})', (t) => {`);
    lines.push(`    t.skip('SpecCaster does not auto-generate ${mt} request bodies; add the body manually in this test (see README).');`);
    lines.push(`  });`);
    lines.push(`});`);
    return lines.join('\n');
  }

  lines.push(`  test('responds per spec', async () => {`);
  lines.push(`    const res = await fetch(${urlExpr}, {`);
  lines.push(`      method: ${JSON.stringify(op.method)},`);
  if (body) {
    const ct = body.contentType.split(';')[0];
    if (body.kind === 'form' || body.kind === 'json' || body.kind === 'text') {
      lines.push(`      headers: { 'content-type': ${JSON.stringify(ct)} },`);
      lines.push(`      body: ${JSON.stringify(body.content)},`);
    }
  }
  lines.push(`    });`);
  lines.push('');
  const keys = expectedStatusKeys(op);
  lines.push(renderStatusAssertion(op, keys));

  if (respVal) {
    lines.push(contentTypeLine(op, respVal));
    lines.push(renderBodyValidation(op, respVal));
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push('');
  return lines.join('\n');
}

function renderTests(spec, opts) {
  const warnings = [];
  const resolver = createResolver(spec, { specFile: opts.spec });
  const baseUrl = opts.baseUrl || serverUrl(spec);
  const ops = collectOperations(spec, resolver);
  const lines = [];
  lines.push(HEADER.trimEnd());
  lines.push('');
  lines.push("const { test, describe } = require('node:test');");
  lines.push("const assert = require('node:assert/strict');");
  lines.push("const { statusAllowed, contentMatches, schemaErrors, formatErrors } = require('./validate');");
  lines.push('');
  lines.push(`const BASE = process.env.SPECCASTER_BASE_URL || ${JSON.stringify(baseUrl)};`);
  lines.push('');
  for (const op of ops) {
    lines.push(renderTest(op, spec, resolver, warnings));
  }
  for (const w of warnings) process.stderr.write(w + '\n');
  return lines.join('\n');
}

function generate(opts) {
  const specFile = opts.spec;
  if (!specFile) throw new Error('--spec is required');
  const spec = loadSpec(specFile);
  const content = renderTests(spec, opts);
  const validateSource = fs.readFileSync(path.join(__dirname, 'runtime-validate.js'), 'utf8');
  return { content, spec, validateSource };
}

function writeGenerated({ content, validateSource, out }) {
  const dir = path.dirname(path.resolve(out));
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(out, content + '\n');
  if (validateSource) fs.writeFileSync(path.join(dir, 'validate.js'), validateSource);
}

module.exports = { generate, loadSpec, writeGenerated, renderTests, HEADER };