const fs = require('fs');
const path = require('path');
const yaml = require('yaml');
const { sampleFromSchema } = require('./sample');

const METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'];
const HEADER = `// AUTO-GENERATED by speccaster. Do not edit by hand.
// Regenerate:  npx speccaster init --spec <spec> --out <file>
// Contract tests derived from your OpenAPI spec. Extend freely:
// the drift gate only checks that the spec and this file stayed in sync.
`;

function loadSpec(file) {
  const raw = fs.readFileSync(file, 'utf8');
  return /\.ya?ml$/i.test(file) ? yaml.parse(raw) : JSON.parse(raw);
}

function resolveRef(ref, spec, base) {
  if (!ref || typeof ref !== 'string') return base;
  const target = ref.replace(/^#\//, '');
  const parts = target.split('/');
  let node = spec;
  for (const p of parts) {
    if (node && typeof node === 'object' && p in node) node = node[p];
    else return base;
  }
  return node && typeof node === 'object' ? node : base;
}

function deref(node, spec) {
  if (!node || typeof node !== 'object') return node;
  if (node.$ref) return deref(resolveRef(node.$ref, spec), spec);
  return node;
}

function pickParamValue(name, location, opParams, spec) {
  const list = opParams || [];
  const p = list.find((x) => x && x.name === name && x.in === location);
  if (!p) return undefined;
  const schema = deref(p.schema || {}, spec);
  return sampleFromSchema(schema);
}

function buildPathSegments(pathStr, opParams, spec) {
  const list = opParams || [];
  return pathStr.replace(/\{([^}]+)\}/g, (m, name) => {
    const p = list.find((x) => x && x.name === name && x.in === 'path');
    const schema = deref(p && p.schema ? p.schema : {}, spec);
    const v = sampleFromSchema(schema);
    return String(v === undefined || v === null ? name : v);
  });
}

function buildQuery(opParams, spec, requiredOnly) {
  const list = opParams || [];
  const qs = [];
  for (const p of list) {
    if (!p || p.in !== 'query') continue;
    if (requiredOnly && !p.required) continue;
    if (p.required) {
      const schema = deref(p.schema || {}, spec);
      qs.push(encodeURIComponent(p.name) + '=' + encodeURIComponent(String(sampleFromSchema(schema))));
    }
  }
  return qs;
}

function expectedStatuses(responses) {
  if (!responses || typeof responses !== 'object') return ['2xx'];
  const codes = Object.keys(responses);
  const success = codes.filter((c) => /^2\d\d$/.test(c));
  if (success.length) return success;
  const redir = codes.filter((c) => /^3\d\d$/.test(c));
  if (redir.length) return redir;
  return codes.length ? codes : ['2xx'];
}

function responseMediaType(responses, code) {
  const resp = responses && responses[code];
  const content = resp && deref(resp.content || {}, {});
  if (!content) return null;
  const keys = Object.keys(content);
  return keys.length ? keys[0] : null;
}

function collectOperations(spec) {
  const ops = [];
  const paths = spec.paths || {};
  for (const p of Object.keys(paths)) {
    const item = paths[p];
    if (!item || typeof item !== 'object') continue;
    for (const m of METHODS) {
      const op = item[m];
      if (!op) continue;
      const mergedParams = (item.parameters || []).concat(op.parameters || []);
      ops.push({
        method: m.toUpperCase(),
        path: p,
        operationId: op.operationId || m.toUpperCase() + ' ' + p,
        summary: op.summary || '',
        params: mergedParams,
        requestBody: op.requestBody,
        responses: op.responses || {},
        tags: op.tags || [],
      });
    }
  }
  return ops;
}

function bodyFor(op, spec) {
  const rb = deref(op.requestBody && op.requestBody.content ? op.requestBody : null, spec);
  if (!rb) return null;
  const content = rb.content || {};
  const keys = Object.keys(content);
  if (!keys.length) return null;
  const media = content[keys[0]];
  const schema = deref(media.schema || {}, spec);
  const value = sampleFromSchema(schema);
  return { content: JSON.stringify(value), contentType: keys[0] };
}

function testName(op) {
  const tag = op.tags && op.tags.length ? op.tags[0] + ' / ' : '';
  return tag + op.method + ' ' + op.path;
}

function renderTests(spec, opts) {
  const baseUrl = opts.baseUrl || (spec.servers && spec.servers.length ? spec.servers[0].url : 'http://localhost:8080');
  const ops = collectOperations(spec);
  const lines = [];
  lines.push(HEADER.trimEnd());
  lines.push('');
  lines.push("const { test, describe } = require('node:test');");
  lines.push("const assert = require('node:assert/strict');");
  lines.push('');
  lines.push(`const BASE = process.env.SPECCASTER_BASE_URL || ${JSON.stringify(baseUrl)};`);
  lines.push('');
  for (const op of ops) {
    lines.push(`describe(${JSON.stringify(testName(op))}, () => {`);
    const segs = buildPathSegments(op.path, op.params, spec);
    const querystring = buildQuery(op.params, spec, true);
    lines.push(`  test('responds per spec', async () => {`);
    const u = '`${BASE}' + segs + (querystring.length ? '?' + querystring.join('&') : '') + '`';
    lines.push(`    const res = await fetch(${u}, {`);
    lines.push(`      method: ${JSON.stringify(op.method)},`);
    const body = bodyFor(op, spec);
    if (body) {
      lines.push(`      headers: { 'content-type': ${JSON.stringify(body.contentType.split(';')[0])} },`);
      lines.push(`      body: ${JSON.stringify(body.content) || 'null'},`);
    }
    lines.push(`    });`);
    const expected = expectedStatuses(op.responses);
    lines.push(`    const okCodes = ${JSON.stringify(expected)};`);
    lines.push(`    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),`);
    lines.push(`      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for ${op.method} ${op.path}');`);
    // content-type soft check
    const respCode = expected.find((c) => /^\d+$/.test(c));
    const mt = respCode ? responseMediaType(op.responses, respCode) : null;
    if (mt) {
      const mainType = mt.split('/')[0].replace(/[^a-z*]/gi, '');
      lines.push(`    const ct = res.headers.get('content-type') || '';`);
      lines.push(`    assert.ok(ct.startsWith(${JSON.stringify(mainType + '/')}), 'expected ${mt}, got ' + ct.split(';')[0]);`);
    }
    lines.push(`  });`);
    lines.push(`});`);
    lines.push('');
  }
  return lines.join('\n');
}

function generate(opts) {
  const specFile = opts.spec;
  if (!specFile) throw new Error('--spec is required');
  const spec = loadSpec(specFile);
  const out = renderTests(spec, opts);
  return { content: out, spec };
}

function writeGenerated({ content, out }) {
  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(out, content + '\n');
}

module.exports = { generate, loadSpec, writeGenerated, renderTests, HEADER };