// Generated by speccaster v0.2.2 — your suite, extend it freely.
// Regenerate from your latest spec, then the drift gate keeps spec / suite in sync:
//   npx speccaster init --spec <spec> --out <file> --force
// These node:test cases are committed to your repo on purpose.
//
// NOTE: generated tests send real traffic. Mutating operations (POST/PUT/PATCH/DELETE)
// will modify the API they hit — point SPECCASTER_BASE_URL at a TEST environment.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { statusAllowed, contentMatches, schemaErrors, formatErrors } = require('./validate');

const BASE = process.env.SPECCASTER_BASE_URL || "http://localhost:8080/v1";

describe("GET /pets", () => {
  const SCHEMA = {"type":"array","items":{"type":"object","required":["id","name"],"properties":{"id":{"type":"integer"},"name":{"type":"string"},"tag":{"type":"string"}}}};
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}` + "/pets", {
      method: "GET",
    });

    assert.ok(statusAllowed(String(res.status), ["200"]),
      'GET /pets — expected status ' + "200" + ', got ' + res.status);

    const ct = res.headers.get('content-type') || '';
    assert.ok(contentMatches("application/json", ct), 'GET /pets — expected application/json, got ' + (ct.split(';')[0] || ct));

    const bodyText = await res.text();
    if (res.status !== 204 && res.status >= 200 && res.status < 300) {
      const errs = schemaErrors((function(){ try { return JSON.parse(bodyText); } catch (e) { throw new Error("GET /pets" + ' — response body is not valid JSON: ' + e.message); } })(), SCHEMA, 'response.body');
      assert.equal(errs.length, 0, formatErrors("GET /pets — response does not match the declared schema", errs));
    }

  });
});

describe("POST /pets", () => {
  const SCHEMA = {"type":"object","required":["id","name"],"properties":{"id":{"type":"integer"},"name":{"type":"string"},"tag":{"type":"string"}}};
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}` + "/pets", {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"name\":\"sample\"}",
    });

    assert.ok(statusAllowed(String(res.status), ["201","422"]),
      'POST /pets — expected status ' + "201/422" + ', got ' + res.status);

    const ct = res.headers.get('content-type') || '';
    assert.ok(contentMatches("application/json", ct), 'POST /pets — expected application/json, got ' + (ct.split(';')[0] || ct));

    const bodyText = await res.text();
    if (res.status !== 204 && res.status >= 200 && res.status < 300) {
      const errs = schemaErrors((function(){ try { return JSON.parse(bodyText); } catch (e) { throw new Error("POST /pets" + ' — response body is not valid JSON: ' + e.message); } })(), SCHEMA, 'response.body');
      assert.equal(errs.length, 0, formatErrors("POST /pets — response does not match the declared schema", errs));
    }

  });
});

describe("GET /pets/{petId}", () => {
  const SCHEMA = {"type":"object","required":["id","name"],"properties":{"id":{"type":"integer"},"name":{"type":"string"},"tag":{"type":"string"}}};
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}` + "/pets/1", {
      method: "GET",
    });

    assert.ok(statusAllowed(String(res.status), ["200","404"]),
      'GET /pets/{petId} — expected status ' + "200/404" + ', got ' + res.status);

    const ct = res.headers.get('content-type') || '';
    assert.ok(contentMatches("application/json", ct), 'GET /pets/{petId} — expected application/json, got ' + (ct.split(';')[0] || ct));

    const bodyText = await res.text();
    if (res.status !== 204 && res.status >= 200 && res.status < 300) {
      const errs = schemaErrors((function(){ try { return JSON.parse(bodyText); } catch (e) { throw new Error("GET /pets/{petId}" + ' — response body is not valid JSON: ' + e.message); } })(), SCHEMA, 'response.body');
      assert.equal(errs.length, 0, formatErrors("GET /pets/{petId} — response does not match the declared schema", errs));
    }

  });
});

