// AUTO-GENERATED by speccaster. Do not edit by hand.
// Regenerate:  npx speccaster init --spec <spec> --out <file>
// Contract tests derived from your OpenAPI spec. Extend freely:
// the drift gate only checks that the spec and this file stayed in sync.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');

const BASE = process.env.SPECCASTER_BASE_URL || "http://localhost:8080/v1";

describe("GET /pets", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pets`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /pets');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("POST /pets", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pets`, {
      method: "POST",
      headers: { 'content-type': "application/json" },
      body: "{\"name\":\"sample\"}",
    });
    const okCodes = ["201"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for POST /pets');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

describe("GET /pets/{petId}", () => {
  test('responds per spec', async () => {
    const res = await fetch(`${BASE}/pets/1`, {
      method: "GET",
    });
    const okCodes = ["200"];
    assert.ok(okCodes.includes(String(res.status)) || (okCodes.includes('2xx') && res.status >= 200 && res.status < 300),
      'expected status ' + okCodes.join('/') + ', got ' + res.status + ' for GET /pets/{petId}');
    const ct = res.headers.get('content-type') || '';
    assert.ok(ct.startsWith("application/"), 'expected application/json, got ' + ct.split(';')[0]);
  });
});

